services:
  - type: web
    name: aqualink-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GEMINI_KEY_FREE
        sync: false
      - key: GEMINI_KEY_PAID
        sync: false
